### ISSUE TITLE
Monitor shuts off after boot screen

### ISSUE THREAD

**Issue by memorable111** [headslive/bugtracker#10]
i am live USB booting heads, monitor switches off after i select a WM in the boot screen, only way to get out is rebooting to my default OS (win 7)

what's the cause of this?

monitor: AcerAL2216W
graphics card: GeForce GT 610

**Comment by parazyd** [comment]
Can you press Tab at the selection screen and append `nomodeset` to the kernel params? This should make you see thing so we can debug further.

**Comment by memorable111** [comment]
Ok, i did that, and it showed me this welcome screen (see pic) https://i.imgur.com/ek96g0H.jpg

everytime i input anything (startx for example) my screen goes blank. only way to get out of this is pressing the power button an when i press it it shows me fast scrolling logs and it shuts off.

**Comment by memorable111** [comment]
Ok, i did that, and it showed me this welcome screen (see pic) https://i.imgur.com/ek96g0H.jpg

everytime i input anything (startx for example) my screen goes blank (Stays black but does not shut off!). only way to get out of this is pressing the power button an when i press it it shows me fast scrolling logs and it shuts off.

**Comment by memorable111** [comment]
Ok, i did that, and it showed me this welcome screen (see pic) https://i.imgur.com/ek96g0H.jpg

everytime i input anything (startx for example) my screen goes blank (Stays black but does not shut off!). only way to get out of this is pressing the power button an when i press it, screen shows me fast scrolling logs and computer shuts off.

**Comment by parazyd** [comment]
It could be that there are missing nvidia drivers... Can you try installing them? I'm not sure exactly which packages those are.

**Comment by parazyd** [comment]
You can also run `heads-generate-debug` as root to create a tarball I can use for debugging.

**Comment by memorable111** [comment]
Hello again! i am very sorry for the late reply

For the Nvidia drivers, Yes, my drivers are all up to date.

As for your second post, yes, i've tried `heads-generate-debug`, it told me to execute it as root 
i try to do that...and it tells me the root auth password is incorrect, and gives me funny messages (the password for root is toor, right?)

**Comment by parazyd** [comment]
That should be the correct password. `sudo` is disabled though, so use `su`.

Sorry for not being more responsive to this.

**Comment by memorable111** [comment]
Thank you! i will now proceed.

**Comment by memorable111** [comment]
For some reason it works now, sorry about the hassle and thank you for your time!

**Comment by parazyd** [comment]
Very well. If you can shed some light on why it works now, please comment here :)
