### ISSUE TITLE
smaller welcome screen

### ISSUE THREAD

**Issue by sigoa** [headslive/bugtracker#16]
https://github.com/sigoa/Merlot/wiki/6-tricks

I made a smaller window doing the same [thing](https://github.com/sigoa/Merlot/blob/master/_modifications/heads-welcome):

**Comment by parazyd** [comment]
There are wmutils in the image, so this can be solved in a more dynamic way. It's possible to figure out the current resolution using `wattr wh $(lsw -r)` and act accordingly.

**Comment by sigoa** [comment]
the EDID string is broken in many monitors it is hard to fix. XRANDR has to be used manually using BASH

wattr wh $(lsw -r)

which gives correct resolution even with broken EDID
