### ISSUE TITLE
solved: no audio until:    pulseaudio -D

### ISSUE THREAD

**Issue by sigoa** [headslive/bugtracker#17]
there is no audio in heads until you run:

pulseaudio -D

see:https://github.com/sigoa/Merlot/wiki/6-tricks

in bash console. neither onboard nor USB audio, which used to work in other Linuces. **alsamixer** looks OK yet no sound to hear.

**Comment by parazyd** [comment]
Yes there is. Audio works perfectly fine.

Where are you experiencing these issues?

**Comment by sigoa** [comment]
gonna check against the original ISO: same there. youtube says pulseaudio is missing. there are reports on hard to unmute soundcards in heads  too. whether this  post is "constructive" or not, I don't know, however, I doubt that I'm the only one experiencing it.

/etc/pulse   and "pulseausio --system" yields error

on a proper Linux, pulseaudio autoconfigures OK, but on heads it fails for some reason, hence no sound.

**Comment by sigoa** [comment]
installing more pulseaudio packages did not help either.

**Comment by parazyd** [comment]
As `luther` start pulseaudio with `pulseaudio -D`. Then you'll get sound in Tor Browser.

For other applications, like `lxmusic`, or `mpv` you don't have to start pulse.

**Comment by sigoa** [comment]
works like a charm now. how to have it autostarted ?

**Comment by parazyd** [comment]
Ideally you'd add it to `awesome.xinitrc` or `openbox.xinitrc` here: https://github.com/headslive/rootfs-overlay/tree/master/usr/local/share/heads
