### ISSUE TITLE
huge /var/log/  files eat all RAM space !

### ISSUE THREAD

**Issue by sigoa** [headslive/bugtracker#18]
somehow that 1 GB of RAM and /shm/ gets eaten up by python2 in a hurry.

no big file to see. maybe kernel issue. how to diagnose ?

after 10 minutes of BitMessage.py all   **no space left on device**  /tmp/

but all files are very small - except thos logs !

**Comment by parazyd** [comment]
Bitmessage is not part of heads' base software so I can't support this. Sorry.

What I can tell you is that you're out of RAM probably, all the files that get written in heads are written to volatile memory (RAM) and how much you can write will depend on the amount of memory you have.

**Comment by sigoa** [comment]
well it is simply **huge LOG files in /var/log**

problem solved  - so I thought...  :camel:
